version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: coffee_drip_game_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/coffee_drip_game_development
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  bundle_cache:
